#!/bin/bash

if [[ -z "$1" ]] ; then
	echo "
	$0 requires two parameters.
	--help for more information.
	Exit.
	"
	exit 
elif [[ "$1" == "--help" ]] ; then
	echo "
	Syntax:
		$0 'dir name' 'output file's name'
	
		Script create folder 'dir name',
		where is created Makefile, name 
		of -o file - 'output file name'.
	" 
elif [[ -z "$2" ]] ; then
	echo "
	$0 requires two parameters.
 	'--help' for more information.
	Exit.
	"	
elif ! [ -d "$1" ] ; then
	mkdir $1
	cd ./$1

	### Makefile ###
	echo "obj=$2.o std.o in_param.o print_help.o
$2: main.c \$(obj)
	gcc $^ -o \$@

clean:
	rm *.o
	" >> Makefile

	### main.c ###
	echo "#include \"std.h\"

int main(int argc, char** argv)
{
	return 0;
}
	"	>> main.c

	### $2.h ###
	echo "#pragma once

int in_param( int argc, char** argv );
void print_help( char** argv );
	" >> $2.h

	### $2.c ###
	echo "#include \"$2.h\"
#include \"std.h\"
	" >> $2.c

	### std.h ###
	echo "#pragma once

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <stdint.h>
#include <inttypes.h>
#include <errno.h>

#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>

#include <err.h>
#include <sys/user.h>
#include <sys/ptrace.h>
#include <syscall.h>

#include \"$2.h\"
	" >> std.h

	### std.c ###
	echo "#include \"std.h\"
	" >> std.c

	### in_param.c ###
	echo "#include \"std.h\"

int in_param(int argc, char** argv)
{
	if(argc<=1)
	{
		printf(\"\\n\\t%s requires more parameters.\\n\"
			\"\\tSee '--help' for more information.\\n\");
	}
	else if(!strcmp(argv[1], \"--help\"))
	{
		print_help(argv[0]);
	}
	else if(!strcmp(argv[1], ""))
	{
			return 1;
	}
	else
	{
		printf(\"\\n\\tUnknown parameter.\\n\\t\"
			\"See '--help' for more information.\\n\");
	}
	return 0;
}
" >> in_param.c
	
	### print_help.c ###
	echo "#include <std.h>

void print_help( char** arg )
{
	printf(\"\\nSyntax:\\n\\t'--func1' : \"
		\"\\n\\t\\tfunc2 : \\n\");
}
" >> print_help.c

	xfce4-terminal -x sh -c "nano README.txt; bash"
       	vi main.c	
	$SHELL	
else
	echo "
	Dir '$1' already exists!
	Exit
"
fi	
